changelog:
  categories:
    - title: 🛠️ Breaking Changes
      labels:
        - breaking
    - title: 🚀 Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📝 Documentation
      labels:
        - docs
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 🔒 Security
      labels:
        - security