name: deploy-docs

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Install dependencies
          run: npm install
        - name: Build docs
          run: npm run docs:build
        - name: Configure GitHub pages
          uses: actions/configure-pages@v2
        - uses: actions/upload-pages-artifact@v1
          with:
            path: docs/.vitepress/dist
        - name: Deploy
          id: deployment
          uses: actions/deploy-pages@v1