name: update-docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.github/workflows/update-docs.yml'

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
      - name: Checkout base code
        uses: actions/checkout@v2
        with:
          path: base-code
      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: docs
      - name: Push to wiki
        run: |
          cd docs
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Add changes" && git push